export {LoginPage} from 'pages/login/login.page';
export {Page404} from 'pages/404/404.page';
export {SignUpPage} from 'pages/signup/signup.page';
export {EmailVerificationPage} from 'pages/email-verification/email-verification.page';
export {MainPage} from 'pages/main/main.page';
export {ExplorePage} from 'pages/explore/explore.page';
export {UserProfilePage} from 'pages/user-profile/user-profile.page';
export {UserProfileEditPage} from 'pages/user-profile-edit/user-profile-edit.page';
export {FollowsPage} from 'pages/follows/follows.page';